### ISSUE TITLE
Toggle commands don't work with mutltiple selection

### ISSUE THREAD

**Issue by kvaleev** [mdickin/vscode-markdown-shortcuts#24] opened 2017-05-01 21:42 UTC
If there are several words selected using multicursor feature, toggle commands works only for the first selection.

**Comment by mdickin** [comment] 2017-05-01 21:50
This looks like a duplicate of #4, do you agree?

**Comment by kvaleev** [comment] 2017-05-01 21:52
Yeah, my mistake. Close this one, please.

**Closed as completed** 2017-05-01 22:45 UTC
Labels: duplicate
